### ISSUE TITLE
active scripts only on page with code

### ISSUE THREAD

**Issue by wayou** [chinhodado/Github-Matches-Highlighter#1]
for now the script is enabled even within pages without code such as profile page, explore...etc.

it will be nicer to active this awesome script only when the page contains codes.

**Comment by chinhodado** [comment]
It should already be restricted to activate on code pages only.

**Comment by wayou** [comment]
oh~ it that so? but seems not working on my side. you can see the screen capture below.

![2015-02-06_133314](https://cloud.githubusercontent.com/assets/3783096/6074972/c4fa1754-ae04-11e4-870c-063628046a44.jpg)

**Comment by wayou** [comment]
never mind. i got the point. the indicator shows there are scripts active but the scripts may not really executed.
